aspects: Update team information
coala/teams pull request #60
Opened 2017-04-15 07:41 UTC by Techievena

Add information about the ongoing projects and team members of the aspects team

2017-04-16 04:47 UTC, Techievena commented
@coala/aspects-developers Please review

2017-04-16 18:03 UTC, userzimmermann requested changes
@Techievena Thanks a lot for those additions! Just remove the links to the obsolete repo based `#aspectsYEAH` projects and we'll merge this :)

2017-04-16 18:03 UTC, userzimmermann commented on README.md
> +-  https://github.com/coala/coala-bears/projects/1
I want to remove the above 2 repo based projects in favor of the org wide `#aspectsYEAH` project below. So better remove those links

2017-04-16 19:54 UTC, Techievena commented on README.md
> +-  https://github.com/coala/coala-bears/projects/1
@userzimmermann Don't you have that `@coala.io`type mail id?

2017-04-17 15:22 UTC, userzimmermann commented on README.md
> +-  https://github.com/coala/coala-bears/projects/1
@Techievena `zimmermann@coala.io` :)

2017-05-04 08:53 UTC, userzimmermann approved these changes

2017-05-04 08:53 UTC, userzimmermann commented
@rultor merge

2017-05-04 08:53 UTC, rultor commented
> @rultor merge

@userzimmermann OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11578-299129982)

2017-05-04 08:54 UTC, rultor commented
> @rultor merge

@techievena @userzimmermann Oops, I failed. You can see the full log [here](http://www.rultor.com/t/11578-299129982) (spent 10s)

```
+ rebase=false
+ container=coala_teams_60
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:coala/teams.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z 'export '\''fork=git@github.com:Techievena/teams.git'\''' ']'
+ cd ..
+ cat
+ '[' false = true ']'
+ cat
+ chmod a+x entry.sh
+ cat
+ echo 'export '\''fork=git@github.com:Techievena/teams.git'\''' ';' 'export '\''fork_branch=aspects'\''' ';' 'export '\''head=git@github.com:coala/teams.git'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_id=60'\''' ';' 'export '\''pull_title=aspects: Update team information'\''' ';' 'echo "Nothing to do."' ';'
+ rm -rf .gpg
+ cd repo
+ git remote add fork git@github.com:Techievena/teams.git
+ git remote update
Fetching origin
Fetching fork
From github.com:Techievena/teams
 * [new branch]      Adrianz/fixingstuff -> fork/Adrianz/fixingstuff
 * [new branch]      adtac/add1 -> fork/adtac/add1
 * [new branch]      adtac/core -> fork/adtac/core
 * [new branch]      adtac/teamadd -> fork/adtac/teamadd
 * [new branch]      aspects    -> fork/aspects
 * [new branch]      master     -> fork/master
 * [new branch]      sils/fixingadriandsstuff -> fork/sils/fixingadriandsstuff
 * [new branch]      sils/lasse -> fork/sils/lasse
 * [new branch]      sims/community -> fork/sims/community
 * [new branch]      sims/template -> fork/sims/template
 * [new branch]      ud/Research -> fork/ud/Research
 * [new branch]      update-community-entry -> fork/update-community-entry
+ args=
+ '[' only == default ']'
+ '[' only == no ']'
+ '[' only == only ']'
+ args=' --ff-only'
+ export BRANCH=__rultor
+ BRANCH=__rultor
++ git show-branch __rultor
++ wc -l
+ '[' 0 -gt 0 ']'
+ git checkout -B __rultor fork/aspects
Switched to a new branch '__rultor'
Branch __rultor set up to track remote branch aspects from fork.
+ git checkout -B master origin/master
Switched to and reset branch 'master'
Branch master set up to track remote branch master from origin.
+ '[' false == true ']'
+ '[' false == true ']'
+ git merge --ff-only __rultor
fatal: Not possible to fast-forward, aborting.
'cid' file is absent, container wasn't started correctly

```

2017-05-04 12:36 UTC, adtac commented
@rultor merge

2017-05-04 12:37 UTC, rultor commented
> @rultor merge

@adtac OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11578-299172479)

2017-05-04 12:37 UTC, rultor commented
> @rultor merge

@techievena @adtac Oops, I failed. You can see the full log [here](http://www.rultor.com/t/11578-299172479) (spent 10s)

```
+ rebase=false
+ container=coala_teams_60
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone git@github.com:coala/teams.git repo
Cloning into 'repo'...
+ cd repo
+ git config user.email me@rultor.com
+ git config user.name rultor
+ '[' -z 'export '\''fork=git@github.com:Techievena/teams.git'\''' ']'
+ cd ..
+ cat
+ '[' false = true ']'
+ cat
+ chmod a+x entry.sh
+ cat
+ echo 'export '\''fork=git@github.com:Techievena/teams.git'\''' ';' 'export '\''fork_branch=aspects'\''' ';' 'export '\''head=git@github.com:coala/teams.git'\''' ';' 'export '\''head_branch=master'\''' ';' 'export '\''pull_id=60'\''' ';' 'export '\''pull_title=aspects: Update team information'\''' ';' 'echo "Nothing to do."' ';'
+ rm -rf .gpg
+ cd repo
+ git remote add fork git@github.com:Techievena/teams.git
+ git remote update
Fetching origin
Fetching fork
From github.com:Techievena/teams
 * [new branch]      Adrianz/fixingstuff -> fork/Adrianz/fixingstuff
 * [new branch]      adtac/add1 -> fork/adtac/add1
 * [new branch]      adtac/core -> fork/adtac/core
 * [new branch]      adtac/teamadd -> fork/adtac/teamadd
 * [new branch]      aspects    -> fork/aspects
 * [new branch]      master     -> fork/master
 * [new branch]      sils/fixingadriandsstuff -> fork/sils/fixingadriandsstuff
 * [new branch]      sils/lasse -> fork/sils/lasse
 * [new branch]      sims/community -> fork/sims/community
 * [new branch]      sims/template -> fork/sims/template
 * [new branch]      ud/Research -> fork/ud/Research
 * [new branch]      update-community-entry -> fork/update-community-entry
+ args=
+ '[' only == default ']'
+ '[' only == no ']'
+ '[' only == only ']'
+ args=' --ff-only'
+ export BRANCH=__rultor
+ BRANCH=__rultor
++ git show-branch __rultor
++ wc -l
+ '[' 0 -gt 0 ']'
+ git checkout -B __rultor fork/aspects
Switched to a new branch '__rultor'
Branch __rultor set up to track remote branch aspects from fork.
+ git checkout -B master origin/master
Switched to and reset branch 'master'
Branch master set up to track remote branch master from origin.
+ '[' false == true ']'
+ '[' false == true ']'
+ git merge --ff-only __rultor
fatal: Not possible to fast-forward, aborting.
'cid' file is absent, container wasn't started correctly

```

2017-05-04 12:37 UTC, adtac commented
@Techievena wanna rebase?

2017-05-04 13:22 UTC, Techievena commented
@adtac was off for a while. Rebasing now. :smile:

2017-05-04 19:41 UTC, userzimmermann requested changes
@Techievena Thanks a lot for doing work of your team leader! ;) And for rebasing! But please remove those 2 outdated project links. Then I will merge it :)

2017-05-04 19:41 UTC, userzimmermann commented on README.md
> +-  https://github.com/coala/coala-bears/projects/1
Oops! Forgot to check that :) Please really remove those 2 links above

2017-05-07 21:37 UTC, userzimmermann approved these changes

2017-05-07 21:37 UTC, userzimmermann commented
@Techievena Wonderful! 🎉

2017-05-07 21:37 UTC, userzimmermann commented
@rultor merge

2017-05-07 21:38 UTC, rultor commented
> @rultor merge

@userzimmermann OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11578-299736848)

2017-05-07 21:39 UTC, merged

2017-05-07 21:40 UTC, rultor commented
> @rultor merge

@userzimmermann Done! FYI, the full log is [here](http://www.rultor.com/t/11578-299736848) (took me 1min)